source 'https://rubygems.org'

gem 'rake'
gem 'haml'
gem 'puma', '>= 5.6.9'
gem 'padrino', '0.15.0'
gem 'vite_padrino', path: '../../vite_padrino'
gem 'vite_ruby', path: '../../vite_ruby'
gem 'pry-byebug'
